### ISSUE TITLE
Question: why is this not baked in pg?

### ISSUE THREAD

**Issue by cemremengu** [postgrespro/zson#20]
Thanks for this!

I am just curious if there is an reason why this cant be baked into pg itself directly as an optimization.

**Comment by afiskon** [comment]
@cemremengu Thanks for the question.

It's difficult to keep all existing (and future) users happy. Imagine the case when all JSON documents are unique, there is no much common data between them to use as a dictionary. Or the case when documents are very small. In this case, an approach similar to the one implemented in ZSON will only degrade the performance. 

You might be interested to learn though that by many requests [I submitted a request to add ZSON to /contrib/](https://www.postgresql.org/message-id/CAJ7c6TP3fCC9TNKJBQAcEf4c%3DL7XQZ7QvuUayLgjhNQMD_5M_A%40mail.gmail.com) so users that want compression could simple use ZSON instead of JSONB, even on Amazon RDS. Please consider joining the thread and letting the community know if the suggested change would be useful.

**Comment by cemremengu** [comment]
Will do thanks! Though, I agree with Markus about submitting it as a builtin type or enhance the jsonb instead of an extension.
